---
- name: Install and configure snipeit as a docker container
  hosts: snipeit_server_docker
  become: true
  gather_facts: true

  vars_files:
    - vars/container.yml   # Load variables from here
  
  tasks:
    - name: Include role tasks
      include_tasks: tasks/main.yml   # Include tasks from here
