---
- name: Install and configure snipeit as a docker container
  hosts: snipeit_server_docker
  become: true
  gather_facts: true
  tasks:
    - name: Include tasks from local tasks directory
      include_tasks: tasks/main.yml
